export interface PersonaRequest {
  ip: string;
  numeroDocumento: string;
}

export interface PersonaResponse {
  ip: string;
  numeroDocumento: string;
  nombres: string;
  apellidoPaterno: string;
  apellidoMaterno: string;
  fechaNacimiento: string;
  edad: number;
  codigoGenero: string;
  tipoEstadoCivil: string;
  digitoVerificacion: string;
  codigoPaisNacimiento: string | null;
  codigoPaisDomicilio: string | null;
  codigoDepartamentoDomicilio: string;
  codigoProvinciaDomicilio: string;
  codigoDistritoDomicilio: string;
  ubigeoDomicilio: string;
  codigoPrefijoDomicilio: string;
  direccionCompleta: string;
  direccionDomicilio: string;
  numeroDireccionDomicilio: string;
  etapaDomicilio: string;
  interiorDomicilio: string;
  descripcionPrefijoInterior: string;
  tipoUrbanizacion: string;
  urbanizacion: string;
  manzanaDomicilio: string;
  loteDomicilio: string;
  descripcionPrefijoBlock: string;
  block: string;
  validado: string | null;
  esMenorEdad: string;
  codigoGradoInstruccion: string;
  nombrePadre: string;
  nombreMadre: string;
  apellidoMaternoMadre: string | null;
  apellidoMaternoPadre: string | null;
  apellidoPaternoMadre: string | null;
  apellidoPaternoPadre: string | null;
  foto: string;
  apellidoCasada: string;
  auditaDni: string | null;
  auditaFecha: string | null;
  auditaIp: string | null;
  codigoDocumentoMadre: string | null;
  codigoDocumentoPadre: string | null;
  codigoDocumentoSustentatorio: string;
  codigoError: string;
  codigoPrefijoDireccion: string | null;
  codigoRestriccion: string;
  codigoTipoFichaRegistro: string | null;
  codigoUbigeoContinenteDomicilio: string | null;
  codigoUbigeoContinenteNacional: string | null;
  codigoUbigeoDepartamentoNacional: string;
  codigoUbigeoDistritoNacional: string;
  codigoUbigeoLocalidadDomicilio: string | null;
  codigoUbigeoLocalidadNacional: string | null;
  codigoUbigeoPaisDomicilio: string | null;
  codigoUbigeoPaisNacional: string | null;
  codigoUbigeoProvinciaNacional: string;
  constVotacion: string;
  descripcionConstVotacion: string;
  descripcionContinenteDomicilio: string | null;
  descripcionContinenteNacional: string | null;
  descripcionDepartamentoDomicilio: string;
  descripcionDepartamentoNacional: string;
  descripcionDistritoDomicilio: string;
  descripcionDistritoNacional: string;
  descripcionDocumentoSustentatorio: string;
  descripcionEstadoCivil: string;
  descripcionGradoInstruccion: string;
  descripcionLocalidadDomicilio: string | null;
  descripcionLocalidadNacional: string | null;
  descripcionPaisDomicilio: string | null;
  descripcionPaisNacional: string | null;
  descripcionPrefijoDireccion: string;
  descripcionPrefijoUrbanizacion: string;
  descripcionProvinciaDomicilio: string;
  descripcionProvinciaNacional: string;
  descripcionRestriccion: string;
  descripcionSexo: string;
  estatura: string;
  fechaCaducidad: string | null;
  fechaDefuncion: string | null;
  fechaExpedicion: string;
  fechaInscripcion: string;
  fichaPdf: string | null;
  flagImagen: string | null;
  idPersona: string | null;
  imagenFirma: string | null;
  longitudFirma: string | null;
  longitudFoto: string;
  numeroDocumentoMadre: string | null;
  numeroDocumentoPadre: string | null;
  numeroDocumentoSustentatorio: string;
  reservado: string;
}
