export const plazosTable = [
  {
    registros: [
      {
        idConfiguraPlazo: '1DF27DCFED696F1BE0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 0,
        distritoFiscal: null,
        idTipoEspecialidad: 0,
        tipoEspecialidad: null,
        idEspecialidad: null,
        especialidad: null,
        idEtapa: null,
        etapa: null,
        idTramite: '000066',
        tramite: 'DISPOSICIÓN DE FORMALIZACIÓN DE INVESTIGACIÓN PREPARATORIA',
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 2,
        plazoAlerta: 28,
        tipoUnidadPlazoAlerta: 2,
        plazoUnidadAlerta: '28 DIAS',
        idTipoComplejidad: 2,
        complejidad: 'SIMPLE',
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 1,
      },
      {
        idConfiguraPlazo: '1DF27ACE4D976EE7E0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 0,
        distritoFiscal: null,
        idTipoEspecialidad: 0,
        tipoEspecialidad: null,
        idEspecialidad: null,
        especialidad: null,
        idEtapa: null,
        etapa: null,
        idTramite: '000066',
        tramite: 'DISPOSICIÓN DE FORMALIZACIÓN DE INVESTIGACIÓN PREPARATORIA',
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 2,
        plazoAlerta: 28,
        tipoUnidadPlazoAlerta: 2,
        plazoUnidadAlerta: '28 DIAS',
        idTipoComplejidad: 2,
        complejidad: 'SIMPLE',
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 2,
      },
      {
        idConfiguraPlazo: '1DF23EA035CF6C36E0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 0,
        distritoFiscal: null,
        idTipoEspecialidad: 0,
        tipoEspecialidad: null,
        idEspecialidad: null,
        especialidad: null,
        idEtapa: null,
        etapa: null,
        idTramite: '000066',
        tramite: 'DISPOSICIÓN DE FORMALIZACIÓN DE INVESTIGACIÓN PREPARATORIA',
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 2,
        plazoAlerta: 28,
        tipoUnidadPlazoAlerta: 2,
        plazoUnidadAlerta: '28 DIAS',
        idTipoComplejidad: 2,
        complejidad: 'SIMPLE',
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 3,
      },
      {
        idConfiguraPlazo: '1DF26AD3F7BF6D0EE0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 0,
        distritoFiscal: null,
        idTipoEspecialidad: 0,
        tipoEspecialidad: null,
        idEspecialidad: null,
        especialidad: null,
        idEtapa: null,
        etapa: null,
        idTramite: '000066',
        tramite: 'DISPOSICIÓN DE FORMALIZACIÓN DE INVESTIGACIÓN PREPARATORIA',
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 2,
        plazoAlerta: 28,
        tipoUnidadPlazoAlerta: 2,
        plazoUnidadAlerta: '28 DIAS',
        idTipoComplejidad: 2,
        complejidad: 'SIMPLE',
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 4,
      },
      {
        idConfiguraPlazo: '1DF23EA035CE6C36E0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 0,
        distritoFiscal: null,
        idTipoEspecialidad: 0,
        tipoEspecialidad: null,
        idEspecialidad: null,
        especialidad: null,
        idEtapa: null,
        etapa: null,
        idTramite: '000066',
        tramite: 'DISPOSICIÓN DE FORMALIZACIÓN DE INVESTIGACIÓN PREPARATORIA',
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 2,
        plazoAlerta: 28,
        tipoUnidadPlazoAlerta: 2,
        plazoUnidadAlerta: '28 DIAS',
        idTipoComplejidad: 2,
        complejidad: 'SIMPLE',
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 5,
      },
      {
        idConfiguraPlazo: '1DBA90ED73E15A03E0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 0,
        distritoFiscal: null,
        idTipoEspecialidad: 0,
        tipoEspecialidad: null,
        idEspecialidad: null,
        especialidad: null,
        idEtapa: null,
        etapa: null,
        idTramite: '000048',
        tramite: 'ACTA DE PRINCIPIO DE OPORTUNIDAD',
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 2,
        plazoAlerta: 28,
        tipoUnidadPlazoAlerta: 2,
        plazoUnidadAlerta: '28 DIAS',
        idTipoComplejidad: 2,
        complejidad: 'SIMPLE',
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 6,
      },
      {
        idConfiguraPlazo: '1DBA90ED73E05A03E0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 2,
        distritoFiscal: 'LIMA',
        idTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        idEspecialidad: '001',
        especialidad: 'COMUN',
        idEtapa: '01',
        etapa: 'CALIFICACIÓN',
        idTramite: null,
        tramite: null,
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 1,
        plazoAlerta: 0,
        tipoUnidadPlazoAlerta: 0,
        plazoUnidadAlerta: ' DIAS',
        idTipoComplejidad: 0,
        complejidad: null,
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 7,
      },
      {
        idConfiguraPlazo: '1DBA90ED73DF5A03E0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 2,
        distritoFiscal: 'LIMA',
        idTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        idEspecialidad: '001',
        especialidad: 'COMUN',
        idEtapa: '01',
        etapa: 'CALIFICACIÓN',
        idTramite: null,
        tramite: null,
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 1,
        plazoAlerta: 0,
        tipoUnidadPlazoAlerta: 0,
        plazoUnidadAlerta: ' DIAS',
        idTipoComplejidad: 0,
        complejidad: null,
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 8,
      },
      {
        idConfiguraPlazo: '1DB9F213FF6C7288E0650250569D508A',
        idTipoPlazo: 4,
        descripcionTipoPlazo: 'Etapa/Trámite',
        idDistritoFiscal: 2,
        distritoFiscal: 'LIMA',
        idTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        idEspecialidad: '001',
        especialidad: 'COMUN',
        idEtapa: '01',
        etapa: 'CALIFICACIÓN',
        idTramite: null,
        tramite: null,
        plazo: 20,
        tipoUnidadPlazo: 4,
        plazoUnidad: '20 DIAS',
        idNivelPlazo: 1,
        plazoAlerta: 0,
        tipoUnidadPlazoAlerta: 0,
        plazoUnidadAlerta: ' DIAS',
        idTipoComplejidad: 0,
        complejidad: null,
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 9,
      },
      {
        idConfiguraPlazo: '1DB9603493C36D75E0650250569D508A',
        idTipoPlazo: 1,
        descripcionTipoPlazo: 'Pre-Etapa',
        idDistritoFiscal: 2,
        distritoFiscal: 'LIMA',
        idTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        idEspecialidad: '001',
        especialidad: 'COMUN',
        idEtapa: '01',
        etapa: 'CALIFICACIÓN',
        idTramite: null,
        tramite: null,
        plazo: 15,
        tipoUnidadPlazo: 1,
        plazoUnidad: '15 DIAS',
        idNivelPlazo: 0,
        plazoAlerta: 0,
        tipoUnidadPlazoAlerta: 0,
        plazoUnidadAlerta: ' DIAS',
        idTipoComplejidad: 0,
        complejidad: null,
        flagDiasCalendarios: '1',
        diasCalendarios: 'SI',
        flagRestrictivo: '0',
        restrictivo: null,
        numeracion: 10,
      },
    ],
    totalPaginas: 1,
    totalElementos: 10,
  },
];

export const tramitesTable = [
  {
    registros: [
      {
        idTramite: null,
        tramite: null,
        codigoTramite: '00001110100111010200004805000',
        codigoCarpetaCuaderno: '000',
        carpetaCuaderno: 'Carpeta principal',
        codigoTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        codigoEspecialidad: '001',
        especialidad: 'COMUN',
        codigoJerarquia: 1,
        jerarquia: 'PROVINCIAL',
        codigoTipoProceso: 1,
        tipoProceso: 'COMUN',
        codigoSubtipoProceso: '01',
        subtipoProceso: 'PROCESO COMUN',
        codigoEtapa: '02',
        etapa: 'PRELIMINAR',
        codigoActoProcesal: '000011',
        actoProcesal: 'PRINCIPIO DE OPORTUNIDAD',
        numeracion: null,
      },
      {
        idTramite: null,
        tramite: null,
        codigoTramite: '00001110100111010100004805000',
        codigoCarpetaCuaderno: '000',
        carpetaCuaderno: 'Carpeta principal',
        codigoTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        codigoEspecialidad: '001',
        especialidad: 'COMUN',
        codigoJerarquia: 1,
        jerarquia: 'PROVINCIAL',
        codigoTipoProceso: 1,
        tipoProceso: 'COMUN',
        codigoSubtipoProceso: '01',
        subtipoProceso: 'PROCESO COMUN',
        codigoEtapa: '01',
        etapa: 'CALIFICACIÓN',
        codigoActoProcesal: '000011',
        actoProcesal: 'PRINCIPIO DE OPORTUNIDAD',
        numeracion: null,
      },
    ],
    totalPaginas: 1,
    totalElementos: 2,
  },
];

export const tramitesSeleccionTramiteTable = [
  {
    registros: [
      {
        idTramite: '000242',
        tramite:
          'AGENDA DE NOTIFICACION DE AUDIENCIA DE REVOCATORIA DE BENEFICIOS PENITENCIARIOS',
        codigoTramite: '00004413100111010600024216000',
        codigoCarpetaCuaderno: '000',
        CarpetaCuaderno: 'Carpeta principal',
        codigoTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        codigoEspecialidad: '001',
        especialidad: null,
        codigoJerarquia: 1,
        jerarquia: 'PROVINCIAL',
        codigoTipoProceso: 1,
        tipoProceso: 'COMUN',
        codigoSubtipoProceso: '01',
        subtipoProceso: 'PROCESO COMUN',
        codigoEtapa: '06',
        etapa: 'SENTENCIA',
        codigoActoProcesal: '000044',
        actoProcesal: 'BENEFICIOS PENITENCIARIOS',
        numeracion: 1,
      },
      {
        idTramite: '000242',
        tramite:
          'AGENDA DE NOTIFICACION DE AUDIENCIA DE REVOCATORIA DE BENEFICIOS PENITENCIARIOS',
        codigoTramite: '00004410100111010600024216000',
        codigoCarpetaCuaderno: '000',
        CarpetaCuaderno: 'Carpeta principal',
        codigoTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        codigoEspecialidad: '001',
        especialidad: null,
        codigoJerarquia: 1,
        jerarquia: 'PROVINCIAL',
        codigoTipoProceso: 1,
        tipoProceso: 'COMUN',
        codigoSubtipoProceso: '01',
        subtipoProceso: 'PROCESO COMUN',
        codigoEtapa: '06',
        etapa: 'SENTENCIA',
        codigoActoProcesal: '000044',
        actoProcesal: 'BENEFICIOS PENITENCIARIOS',
        numeracion: 2,
      },
      {
        idTramite: '000194',
        tramite: 'AGENDA DE NOTIFICACION DE AUDIENCIA DE REVOCATORIA',
        codigoTramite: '00003613100111010600019416000',
        codigoCarpetaCuaderno: '000',
        CarpetaCuaderno: 'Carpeta principal',
        codigoTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        codigoEspecialidad: '001',
        especialidad: null,
        codigoJerarquia: 1,
        jerarquia: 'PROVINCIAL',
        codigoTipoProceso: 1,
        tipoProceso: 'COMUN',
        codigoSubtipoProceso: '01',
        subtipoProceso: 'PROCESO COMUN',
        codigoEtapa: '06',
        etapa: 'SENTENCIA',
        codigoActoProcesal: '000036',
        actoProcesal: 'REVOCATORIA DE PENA RESERVA DE FALLO CONDENATORIO',
        numeracion: 3,
      },
      {
        idTramite: '000194',
        tramite: 'AGENDA DE NOTIFICACION DE AUDIENCIA DE REVOCATORIA',
        codigoTramite: '00003610100111010600019416000',
        codigoCarpetaCuaderno: '000',
        CarpetaCuaderno: 'Carpeta principal',
        codigoTipoEspecialidad: 1,
        tipoEspecialidad: 'PENAL',
        codigoEspecialidad: '001',
        especialidad: null,
        codigoJerarquia: 1,
        jerarquia: 'PROVINCIAL',
        codigoTipoProceso: 1,
        tipoProceso: 'COMUN',
        codigoSubtipoProceso: '01',
        subtipoProceso: 'PROCESO COMUN',
        codigoEtapa: '06',
        etapa: 'SENTENCIA',
        codigoActoProcesal: '000036',
        actoProcesal: 'REVOCATORIA DE PENA RESERVA DE FALLO CONDENATORIO',
        numeracion: 4,
      },
    ],
    totalPaginas: 1,
    totalElementos: 4,
  },
];
