export enum ConstanteMenuUsuario {
  PERFILES_USAURIO = 'PERFILES_USUARIO',
  DEPENDENCIA_USUARIO = 'DEPENDENCIA_USUARIO',
  BAJA_USUARIO = 'BAJA_USUARIO',
  HABILITAR_USUARIO = 'HABILITAR_USUARIO',
  BLOQUEAR_USUARIO = 'BLOQUEAR_USUARIO',
  DESBLOQUEAR_USUARIO = 'DESBLOQUEAR_USUARIO',
  ADMINISTRADOR_DISTRITAL = 'ADMINISTRADOR_DISTRITAL',
}
