export const data = [
  {
    id: 1,
    logo: '',
    codigo: 12,
    nombre: 'Analista',
    nombre_plural: 'Carpeta fiscal',
    padre: 'Administrador',
    icono: 'icono 1',
    sadId: 12,
    orden: 2,
    estado: 'inactivo',
  },
  {
    id: 2,
    logo: 'https://picsum.photos/101',
    codigo: 14,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 3,
    logo: 'https://picsum.photos/102',
    codigo: 18,
    nombre: 'PB',
    nombre_plural: 'PB',
    padre: 'Sistemas',
    icono: 'memory',
    sadId: 11,
    orden: 1,
    estado: 'activo',
  },
  {
    id: 4,
    logo: 'https://picsum.photos/103',
    codigo: 13,
    nombre: 'Analista 2',
    nombre_plural: 'Analista 2',
    padre: 'Sistemas',
    icono: 'security',
    sadId: 13,
    orden: 2,
    estado: 'inactivo',
  },
  {
    id: 5,
    logo: 'https://picsum.photos/104',
    codigo: 12,
    nombre: 'Analista',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Administrador',
    icono: 'icono 1',
    sadId: 12,
    orden: 2,
    estado: 'inactivo',
  },
  {
    id: 6,
    logo: 'https://picsum.photos/105',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 7,
    logo: 'https://picsum.photos/106',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 8,
    logo: 'https://picsum.photos/107',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 9,
    logo: 'https://picsum.photos/108',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 10,
    logo: 'https://picsum.photos/109',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 11,
    logo: 'https://picsum.photos/110',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 12,
    logo: 'https://picsum.photos/111',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 13,
    logo: 'https://picsum.photos/112',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 14,
    logo: 'https://picsum.photos/113',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 15,
    logo: 'https://picsum.photos/114',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 16,
    logo: 'https://picsum.photos/115',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 17,
    logo: 'https://picsum.photos/116',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
  {
    id: 18,
    logo: 'https://picsum.photos/117',
    codigo: 17,
    nombre: 'Carpeta Fiscal Electronica',
    nombre_plural: 'Carpeta Fiscal Electronica',
    padre: 'Sistemas',
    icono: 'icono 2',
    sadId: 14,
    orden: 2,
    estado: 'activo',
  },
];
